#!/bin/bash
#pip install $(pip list --outdated --format=legacy | awk '{ print $1 }') --upgrade
#pip list --outdated | cut -d' ' -f1 | xargs pip install --upgrade
#pip list --outdated --format=freeze > requirements.txt && pip install --upgrade -r requirements.txt && rm requirements.txt
pipdate
